### ISSUE TITLE
Remove bubbles and numbers

### ISSUE THREAD

**Issue by nigep7** [booncon/slippry#101]
Excellent slider, thanks, is there a way to remove the bubbles and numbers?

**Comment by vladmirom** [comment]
You can remove pager bubbles just adding settings to your slippry in js to pager: false;
Can you specify which numbers do you mean?

**Comment by nigep7** [comment]
Thanks, that worked all sorted.
Numbers: I naively removed the 'Bubbles' section from the CSS at one point.

On 7 March 2016 at 09:28, Vladimir <notifications@github.com> wrote:

> You can remove pager bubbles just adding settings to your slippry in js to
> pager: false;
> Can you specify which numbers do you mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/booncon/slippry/issues/101#issuecomment-193177874>.
>



-- 
Nigel Pennington
07890 640338

**Comment by vladmirom** [comment]
Okay :) We close the issue for now. If you have any other questions, you can contact us at: support@pixels.fi

**Comment by nigep7** [comment]
Much appreciated. How can I make the left and right arrows permanently visable as opposed to hover?

**Comment by vladmirom** [comment]
You can use controlClas to add the css class for controls that you need. The same way as removing pager.
