### ISSUE TITLE
compass requirement

### ISSUE THREAD

**Issue by someother1** [booncon/slippry#104]
Is there a way to avoid the "compass" requirement?
Eg. for the mixins, could i use bootstrap or manual written mixins instead?

i can read @ https://github.com/booncon/slippry/issues/73 that compass will be removed in future releases - but this information is more then 1 year ago.

Is this project alive?

**Comment by sftsk** [comment]
Thanks for the question, the project is still alive!

You can just rewrite the bundled stylesheet to work without Compass as a quick fix, it is barely used anyway.

Like said in the past, this should be fixed in the next big update which is just going through the last parts of the planning phase.

**Comment by sftsk** [comment]
This has been solved now, removed Compass as a dependency and included autoprefixer into the build chain
