### ISSUE TITLE
Second News Slide is Blank

### ISSUE THREAD

**Issue by pfhenley86** [booncon/slippry#106]
Hi,

I was wondering if anyone could help me figure out why my second news slide is blank? It looks like everything is printing out right but the positioning is not changing. You can see it here.

http://poweralley.webrestserver.com/

**Comment by uchedestiny01** [comment]
Hello,
The link you gave isn't working...

**Comment by pfhenley86** [comment]
That was the production site. I have it working now. I don't 100% remember how I fixed it but I think it was a Drupal issue and not the slider. I forgot to update this after I fixed it.

**Comment by uchedestiny01** [comment]
Ok!

**Comment by sftsk** [comment]
Yay, glad you've fixed it :)
