### ISSUE TITLE
Removing Pager Bubbles

### ISSUE THREAD

**Issue by uchedestiny01** [booncon/slippry#112]
Hello, am happy to see + use this GREAT responsive slider... big thanks to the Crafted Team.

Is there any way for me to remove the Pager Bubbles?

My image height location is filled up and I don't want to reduce the image height, I want to remove the Pager Bubbles... how do I achieve that if possible?

Thanks!

**Comment by sftsk** [comment]
Thanks for the kind words :)

Take a look at this: http://slippry.com/settings/#pager

If you set pager to false the bubbles will disappear!

**Comment by uchedestiny01** [comment]
Thanks! I have achieved what I needed!
