### ISSUE TITLE
Problem with jquery 3.1

### ISSUE THREAD

**Issue by mkermani144** [booncon/slippry#113]
When I try to use `jquery 3.1` with `slippry`, I got the following error:
> Uncaught TypeError: Cannot read property 'indexOf' of undefined

Is `slippry` incompatible with `jquery 3.1`?

**Comment by sftsk** [comment]
have not tested this yet but if this is the error you are getting most likely not :-/

**Comment by dsp1986** [comment]
I just had the same problem. will this be fixed? "written with the future in mind" sounded promising. 
It took a while for me to find the right solution (which was cloning jquery repo and using version 1.10.2, loading from cdn like in example didn't seem to work for me)
nice plugin otherwise :+1:

**Comment by sftsk** [comment]
of course this should be fixed, I am just a little swamped with other work at the moment :( Happy to take in any pull requests!

**Comment by wouter140** [comment]
The problem seems to be the .load(). This is removed since 1.8. Looked into sollution, but everything I tried seems to break the initialisation.

**Comment by wouter140** [comment]
Created a pull request with changed that fix the problem.

**Comment by sftsk** [comment]
Thanks @wouter140 , merged your request and did a small fix to it. Now it works fine on the current jQuery.
