### ISSUE TITLE
How to resize image slider

### ISSUE THREAD

**Issue by PriaM1** [booncon/slippry#114]
HI,

Sorry if this has been covered, can't seem to find the answer.  In the demo version the size of each image is 774px, but I can't seem to find where I can adjust the sizing of the image?

Thank you in advance for your help and thanks for a great responsive slider.

**Comment by sftsk** [comment]
Hello,

Slippry uses whatever content it gets, it won't resize the image sizes. The only thing it does is resize the slider responsively according to the image proportions.

Just upload the image in a size big enough for the biggest screens and don't worry. If you want to do some next level responsive images you may want to take a look at using http://caniuse.com/#feat=srcset within Slippry.

All the best,
I hope this helps!
