### ISSUE TITLE
Use caption for pager

### ISSUE THREAD

**Issue by dan121** [booncon/slippry#115]
Any idea how to use the caption text instead of numbers for the pager?
Instead of 1, 2, 3, 4 etc, I'd like it to use the title or alt attribute from the image as the link text.

**Comment by sftsk** [comment]
Hello,

that needs some custom coding. You may look at this example: http://slippry.com/examples/thumbnails/

Basically create a pager yourself where you run through all the slides, fetch the captions and add them as links somewhere in your code.
Then use the Slippry callbacks to register those links to advance to the according slides :)

I hope this helps!
