### ISSUE TITLE
Problems when using in auto mode and not having the element visible

### ISSUE THREAD

**Issue by wouter140** [booncon/slippry#119]
Hey,

I'm using this in a popup which will not be shown until the user presses a button.
I'm using it in auto mode.
While I have the element invisible in css with "display: none" the sliding just breaks until a random moment.
I figured out the problem and it seems to be that the "transitionDone" function does not get called when a transition is done while the element is invisible. You have a "moving" variable that has to be false for a new transition to be able to happen. But since the transitionDone function does not get called the variable is not set back to false.

I fixed this for myself by only transitioning while the element is visible.
This is a working fix for me since I don't need it to transition to a different image while it is not visible, but this might be a problem for someone else that is expecting it to transition while invisible. 
If you want I can create a pull request with my fix.

**Comment by sftsk** [comment]
Hey,

thanks for you observations, a pull request would be highly appreciated as I can imagine others might get into the same problem!
