### ISSUE TITLE
example suggestion

### ISSUE THREAD

**Issue by newschapmj1** [booncon/slippry#121]
I like the 4 examples

Thumbnails has sass for the css. This may be a barrier to users like me who have not used it.
I suggest you include a css version to remove the barrier.
 http://slippry.com/examples/thumbnails/

It took me a while to use http://www.sassmeister.com/ and find mixins that worked.

==================

I changed border-color to blue as I could not convert it.

css version 

fixed css

/* Thumbnails */
.thumb-box {
  padding: 1.4em 0 1em;
  margin-left: -1%;
  width: 102%;
}
.thumb-box .thumbs:before, .thumb-box .thumbs:after {
  content: "";
  display: table;
}
.thumb-box .thumbs:after {
  clear: both;
}
.thumb-box .thumbs li {
  float: left;
  width: 25%;
  text-align: center;
  padding: 0 1%;
}
.thumb-box .thumbs li img {
  width: 100%;
  opacity: .8;
  -moz-transition: opacity 0.32s;
  -o-transition: opacity 0.32s;
  -webkit-transition: opacity 0.32s;
  transition: opacity 0.32s;
  border-bottom: 4px solid transparent;
}
.thumb-box .thumbs li img.active {
  border-color: blue;
  opacity: 1;
}
.thumb-box .thumbs li:hover img {
  opacity: 1;
  -moz-transition: opacity 0.2s;
  -o-transition: opacity 0.2s;
  -webkit-transition: opacity 0.2s;
  transition: opacity 0.2s;
}

**Comment by neo125874** [comment]
thanks for your sharing, i finally noticed that was not typically css!
thank you @newschapmj1

**Comment by sftsk** [comment]
thank you for this @newschapmj1 , I am sure it will help others!
You can of course check the css file from the Slippry website itself to get the styles: http://slippry.com/assets/css/styles.css
