### ISSUE TITLE
npm install slippry

### ISSUE THREAD

**Issue by ohpyupi** [booncon/slippry#125]
I installed slippry package through npm. And that contained deprecated load() function.
I spent time to fixing load() to .on('load') and trigger('load') to use it with jquery 3.

However, I just figured out slippry in this repository already has fixed jquery3 compatible issue...!!!
Please update slippry in npm for peope who use npm when installing dependencies!

**Comment by sftsk** [comment]
I am very sorry about this, I have just updated npm to the newers version. I thought this would work automatically after releasing a new version to Github.
