### ISSUE TITLE
Height isn't easy to define

### ISSUE THREAD

**Issue by grimaldo** [booncon/slippry#60]
I can't set the height of the slider, I'm loading images with 570px but the slider's wrapper is just 370px, Im using the 'adaptiveHeight' parameter in true. But is not working.

You can see it in:: http://dev.gardel.com.mx

There is a setting to fix it? thank you

**Comment by sftsk** [comment]
Hello,
to me is seems like the height is right, what browser are you using?
`adaptiveHeight = true` is only needed if the content has different heights, otherwise keep it to false.
