### ISSUE TITLE
Slippry slider plugin in joomla

### ISSUE THREAD

**Issue by ducklin5** [booncon/slippry#61]
Ive grown really fond Slippry and its really easy to use, but I'm changing CMS from pyrocms to joomla, and they only way it could work is as a module, is anyone willing to help with the project.

**Comment by sftsk** [comment]
sounds very interesting, keep me posted :)

**Comment by ducklin5** [comment]
Here it is: https://github.com/ducklin5/Slippry-joomla
Again, its really simple. You have to input the code the way you normally would, but it allows you to use Slippry as a module in jommla. Its a way to avoid the code filtering. If anyone more experienced with joomla is interested, the module has alot of room for improvement.

**Comment by sftsk** [comment]
Cool, thank you for this!
