### ISSUE TITLE
Path to image assets + fix

### ISSUE THREAD

**Issue by lordspace** [booncon/slippry#62]
Hi,

Awesome job with the slider!

I noticed that the 2 images mentioned in the slippry.css were loaded from /images/
In my projects I like putting external projects into share/ folder.

All I had to do is just update dist/slippry.css to load images from ../images/ i.e. 1 level up.

Slavi

**Comment by sftsk** [comment]
thanks for the feedback, might be helpful to somebody :)

**Comment by sjelfull** [comment]
@sftsk I think it should be relative by default.

**Comment by lordspace** [comment]
me too

**Comment by Anahkiasen** [comment]
I think it should be relative as well

**Comment by drewbaker** [comment]
I think you shouldn't include any images. Look at the way [Cycle2](http://jquery.malsup.com/cycle2/api/) handles next/prev buttons for an example of the bets way to do it in my opinion.
