### ISSUE TITLE
setTimeout Conflict

### ISSUE THREAD

**Issue by jej12** [booncon/slippry#63]
The slider is working on our site, however I want to add a setTimeout function to the same page that will delay a modal from appearing. Separately, both work fine, however there seems to be a conflict which I can't identify when both are used.

I'm calling the slider using:
    jQuery('#slider').slippry({
        adaptiveHeight: false,
        controls: true,
        pause: 8000,
        autoDelay: 5000
        });

This how I'm trying to setTimeout:
        setTimeout(function() {
          $('#signUpModal').modal('show');
        }, 2000);

**Comment by sftsk** [comment]
that is strange as all the internal functions of slippry shouldn't affect anything outside and vice versa. Will have to look into this.
in the meantime can you just name your function differently?

**Comment by sftsk** [comment]
I have tried recreating this and could not find any problem. What exactly is conflicting? The two timeouts don't interfere in a demo I just built.

**Comment by sftsk** [comment]
closed for inactivity
