### ISSUE TITLE
Static content on top of slideshow

### ISSUE THREAD

**Issue by jmvn** [booncon/slippry#67]
Is it possible to add static content on top of the slideshow? I've tried setting it with absolute positioning but can't get it to work. Would like to add a site logo and a main menu, similar to the attachment below. Can it be done?

Many thanks in advance!

![slippry](https://cloud.githubusercontent.com/assets/6805750/6595781/2b496234-c7f6-11e4-92b2-3ba5e767a325.png)

**Comment by sftsk** [comment]
you can probably achieve this with absolute positioning of the content.
make sure logo + menu get a higher z-index than the slippry container and position them absolute. position the slippry container absolute and add that all to a container with relative positioning.
then it is only about positioning the elements. all should have a `top: 0` and the logo + slippry `left: 0`, the menu `right: 0`

I hope this helps, all the best!

**Comment by jmvn** [comment]
Thanks for the quick reply! Got it working now, thought I had it setup just like that before as well but must have missing something.

One issue however: since the slider is now positioned absolutely, if overflows the content below and setting a fixed height isn't really possible. If I understand things correctly, the height is set by the fillerClass but this can't affect the content below anymore. Is there any way to get the calculated top padding to a element outside the slider?

**Comment by jmvn** [comment]
Never mind the idiot. The slideshow class doesn't have to be positioned absolutely. All is well except for my coding skills.

**Comment by sftsk** [comment]
:) glad you worked it out!
