### ISSUE TITLE
 File to import not found or unreadable: compass.

### ISSUE THREAD

**Issue by r670615769** [booncon/slippry#73]
I want change slipppry.css.So rebuilding slippry.scss.but I can't found  compass.
the error is " File to import not found or unreadable: compass."

**Comment by sftsk** [comment]
Hello,
unfortunately `t the moment slippry uses the http://compass-style.org library to generate it's stylesheets. in the next big release we will take that out.
For the moment please make sure you have compass installed when compiling the sass.

Cheers!
