### ISSUE TITLE
No issue, just need some help....and didn't know where/how to ask

### ISSUE THREAD

**Issue by TerrySchroeder** [booncon/slippry#74]
This is  such great software! I grew up on COBOL and FORTRAN so having a little problem using JQuery. I downloaded and tried to come up with thumbnails. I tried your instructions on your web site but could not figure out how to make the download code work like your online version. Can you point me to some code???

**Comment by manatarms** [comment]
Hey Terry, 
Great to hear that you're a COBOL and FORTRAN coder. 

Usually I download the entire project for any Jquery Plugin then navigate to the demo folder. There should be an index page that should work correctly in your browser right from the start. Open this file in your favorite code editor, I prefer sublime text. Take a look at what's happening in the code to get a feel for the Plugin. Let me know how it goes. 
Cheers

**Comment by sftsk** [comment]
Hello,
glad to hear you like slippry.
If you clone this git repository you will find all the demoes in the following branch: https://github.com/booncon/slippry/tree/demo

This is a middleman project but more or less you should be able to find all the necessary code!

I hope this helps, all the best :)

**Comment by TerrySchroeder** [comment]
HI,

Thank you for trying to help me! Don't get old...well I guess it is better than the alternative. Anyway, I have spent hours trying to get this to work and nothing. I have attached the html file I've been working with and maybe you can see something. I'm to the point in my life that if it  doesn't bite me I don't see it, just ask my wife.

Thank you again,

Terry

**Comment by manatarms** [comment]
Hey Terry,

I'm happy to take a look at your code.But I can't see any attached file.
It'll be great if you could also send your supporting files (maybe zip the
folder you're working in and send that)
.
Cheers

**Comment by TerrySchroeder** [comment]
Hi,

Believe it or not, after 3 pots of coffee (and a cookie or two) I finally got it to work!!!!

I think I need to take a nap...

Anyway,

Thank you for offering to help.

Terry

PS. I may be in touch in the near future........

**Comment by manatarms** [comment]
That's great!!! 

Yes please feel free to get in touch. 


Cheers 

On March 30, 2015 6:24:36 AM GMT+05:30, TerrySchroeder <notifications@github.com> wrote:
>Hi,
>
>Believe it or not, after 3 pots of coffee (and a cookie or two) I
>finally got it to work!!!!
>
>I think I need to take a nap...
>
>Anyway,
>
>Thank you for offering to help.
>
>Terry
>
>PS. I may be in touch in the near future........
>
> 
>
>From: manatarms [mailto:notifications@github.com] 
>Sent: Sunday, March 29, 2015 12:32 PM
>To: booncon/slippry
>Cc: TerrySchroeder
>Subject: Re: [slippry] No issue, just need some help....and didn't know
>where/how to ask (#74)
>
> 
>
>Hey Terry,
>
>I'm happy to take a look at your code.But I can't see any attached
>file.
>It'll be great if you could also send your supporting files (maybe zip
>the
>folder you're working in and send that)
>.
>Cheers
>
>On Sun, Mar 29, 2015 at 5:43 PM, TerrySchroeder
><notifications@github.com>
>wrote:
>
>> HI,
>>
>> Thank you for trying to help me! Don't get old...well I guess it is
>better
>> than the alternative. Anyway, I have spent hours trying to get this
>to work
>> and nothing. I have attached the html file I've been working with and
>maybe
>> you can see something. I'm to the point in my life that if it doesn't
>bite
>> me I don't see it, just ask my wife.
>>
>> Thank you again,
>>
>> Terry
>>
>>
>>
>> From: manatarms [mailto:notifications@github.com]
>> Sent: Friday, March 27, 2015 10:08 PM
>> To: booncon/slippry
>> Cc: TerrySchroeder
>> Subject: Re: [slippry] No issue, just need some help....and didn't
>know
>> where/how to ask (#74)
>>
>>
>>
>> Hey Terry,
>> Great to hear that you're a COBOL and FORTRAN coder.
>>
>> Usually I download the entire project for any Jquery Plugin then
>navigate
>> to the demo folder. There should be an index page that should work
>> correctly in your browser right from the start. Open this file in
>your
>> favorite code editor, I prefer sublime text. Take a look at what's
>> happening in the code to get a feel for the Plugin. Let me know how
>it
>> goes.
>> Cheers
>>
>> —
>> Reply to this email directly or view <
>> https://github.com/booncon/slippry/issues/74#issuecomment-87153273>
>it on
>> GitHub. <
>>
>https://github.com/notifications/beacon/AF-1AE9KeI4a5_ZKYW85QVgosCs34Sgpks5n5hJ5gaJpZM4D2NYF.gif>
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/booncon/slippry/issues/74#issuecomment-87403985>.
>>
>
>
>
>—
>Reply to this email directly or view
><https://github.com/booncon/slippry/issues/74#issuecomment-87449172> 
>it on GitHub. 
><https://github.com/notifications/beacon/AF-1AO_tC6_ZCQefvixtHS-Ui_LUK5k-ks5n6C6XgaJpZM4D2NYF.gif>
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/booncon/slippry/issues/74#issuecomment-87504792

-- 
Sent from my Android device.

**Comment by TerrySchroeder** [comment]
Hi,

Somehow I knew I would be contacting you again... 

I am trying to re-work my web site and make it responsive and nicer looking, www.thedrywallartist.com 

How do I make the thumb nail container across the bottom scroll horizontally?

How do I change the size of the thumbnails?

How do I put controls on the thumbnails, ie. move left to right or right to left?

 

Do you know of a site that has something like this? I can go there and figure it out from there, maybe... 

 

I have about 15 slides I need to have on a given page.

By the way, What is your name?

Terry

**Comment by sftsk** [comment]
Glad you have worked it out :)

**Comment by manatarms** [comment]
Hey Terry,

Could you be a little more specific as to what you want to do. Everything
is possible with a little javascript. I'm happy to point you to some pages
if you can be a little clearer about what you want the final result to be.

Cheers
