### ISSUE TITLE
adaptiveheight does not fire on window resize, killing responsive designs

### ISSUE THREAD

**Issue by whatsnewsisyphus** [booncon/slippry#76]
Hola,
Just wanted to put in this quick bug report. If you have a responsive website where your slides might change height without a fixed ratio, for example, if you have an image with bunch of text underneath and the text gets spread across more lines as the container gets narrower, the slider accommodates for width but not height until you click next slide, chopping off content on the bottom.

Real life use case, you come to a website on your tablet, decide reading it in portrait mode is going to be easier, you turn your tablet and snip, half the text is gone.

**Comment by sftsk** [comment]
hey, sorry for only catching this now.
in this case you need to hook into the `window.resize()` function with js and call `refresh()` on Slippry or you can set up different CSS rules in media-queries to handle this.

Unfortunately when content gets complex it is difficult to guess what can be done automatically to deal with changes in size.
