### ISSUE TITLE
fade sticks on Chrome

### ISSUE THREAD

**Issue by thankyouverymuch** [booncon/slippry#79]
I tested the script and I have to say "This is great!!"
Thanks for sharing this great script.

I just found one problem.
When I use fade effect and set "speed=3000 pause=5000", pictures do not dissolve smoothly. It happens only on Chrome.
Default setting works just fine. 

Do you know any issue that relates to Chrome and Javascript?

**Comment by sftsk** [comment]
Hmm, that sounds strange. not sure what the problem could be but can you play around with different values and see if it changes anything?
Also css animations/ transitions unfortunately sometimes cause browsers to do funny things as they are still not 100% standardised.

Let me know if other values work better.

**Comment by thankyouverymuch** [comment]
sftsk, Thanks for your reply.
I'll try to use different values.
I really need to make it slow dissolve.
