### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by crgwbr** [booncon/slippry#80]
This repo already has a package.json file, but it doesn't seem to be published to the NPM registry. Doing so would make it much easier to include in other projects. Would it be possible to publish?

**Comment by sftsk** [comment]
thanks for the input. have added it there. pushed it first with the wrong version number and now for some reason it does not update.
will probably be fixed with the next release but i hope this works already!

**Comment by crgwbr** [comment]
Excellent, thanks @sftsk!
