### ISSUE TITLE
add image on the fly

### ISSUE THREAD

**Issue by ioogaa** [booncon/slippry#83]
it's not issue but I don't know where to ask.
is there any sample code to add image on the fly..?
I try to add image every 5 second but new image that I append not show in the slider.
```
var refreshId = setInterval( function() 
		    {
		    	
		    	$.get('{{ url('data_slide') }}', function(data) {

		    		gallery.append(data)
		    		gallery.refresh();
				});

		    }, 5000);
```

**Comment by sftsk** [comment]
This http://slippry.com/settings/#refresh would be the right function to call after adding content dynamically.
Is `gallery` in your code the initialised Slippry instance?
Check here http://slippry.com/examples/thumbnails/ for an example of how to use the Slippry functions on an instance.

Also make sure you add the DOM elements in the right data format into the Slippry container. From your function I can't tell what you are getting with your call. (Can you check with the web inspector if anything actually gets added to the Slippry wrapper?).

Good luck!

**Comment by sftsk** [comment]
will close this as I have not heard anything!
