### ISSUE TITLE
How to add a custome width height on a image inside a slider

### ISSUE THREAD

**Issue by usamamashkoor** [booncon/slippry#84]
How to add a custome width height on a image inside a slider
here is my HTML
Kindly see the image in below comment to see my html because i was having problem pasting the code here

and my jqyuery is 
jQuery('#out-of-the-box-demo').slippry();
kindly help me

**Comment by usamamashkoor** [comment]
<div class="sy-slides-wrap" >
			<ul id="out-of-the-box-demo">
			  <li>
			    <a href="#slide1">
			      <img src="assets/img/1.png" alt="">
			
			    </a>
			  </li>
			  <li>
			    <a href="#slide2">
			      <img src="assets/img/slider2.png"  >
			    
			    </a>
			  </li>
			  
			</ul>
		</div>

**Comment by usamamashkoor** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8676339/8859846/5dc2c09a-3199-11e5-8590-3019c6666def.png)

**Comment by sftsk** [comment]
Hey, I am not sure if I understand your question but probably just add something like:

```
.sy-slides-wrap img {
 height: 300px; // or a max-height: 300px; or whatever you would like to do!
}
```

I hope this helps,
cheerio!

**Comment by usamamashkoor** [comment]
Thanks it fixed my issue Thanks for you help @sftsk sftsk
