### ISSUE TITLE
Missing UL classes after .destroySlider()

### ISSUE THREAD

**Issue by ashep** [booncon/slippry#86]
After .destroySlider() is called, classes of the UL element are not restored.

**Comment by sftsk** [comment]
Hmm, that should not happen and has definitely worked in the past.
Will look into this, thanks for pointing out!

**Comment by sftsk** [comment]
Finally looked into this.
This does not work with recent jQuery versions anymore:
http://api.jquery.com/attr/

They changed some behaviour:
>As of jQuery 1.6, the .attr() method returns undefined for attributes that have not been set. To retrieve and change DOM properties such as the checked, selected, or disabled state of form elements, use the .prop() method.

Will work on a fix, thanks for pointing it out.

**Comment by dzena** [comment]
@sftsk 
any news on the fix?

**Comment by sftsk** [comment]
sorry @dzena nothing yet :-/
swamped with other work :(

**Comment by dzena** [comment]
Thank's for the quick response. :)

Im also swamped, but if I find some time in the future, ill submit a PR.

Keep the good work.
