### ISSUE TITLE
There is no option for captions to inherit links from image

### ISSUE THREAD

**Issue by hadi77ir** [booncon/slippry#87]
I was going to make a slideshow for the front page of my site but there is no simple way to make captions inherit links from image and I have to specify link in its "alt" attribute.
Is there any way to do this?
Note: I am using demo slideshow as basis.

**Comment by SeenNotHurd** [comment]
Hi @hadi77ir 

Can you clarify a little what you mean by "inheriting links from an image"?

**Comment by hadi77ir** [comment]
I mean to link the captions exactly to what images are linked to :)

**Comment by sftsk** [comment]
That get's tricky. as you can not have a link within a link you could then not have links to other places within the caption.
Probably the only way is if you manually add the link (let your cms do it) around the whole text in the caption.
Sorry but this won't be changed as the scenario you describe doesn't seem to be the one we would like to use as the "default" state.

Thank you and all the best!
