### ISSUE TITLE
slides of the "news slider-example" don't stay at the same spot..

### ISSUE THREAD

**Issue by shinichi11** [booncon/slippry#88]
i tried to implement the news-slider style and everything works fine but even though i used the same image for all three slides the second and third slide come up a little lower...

![example1](https://cloud.githubusercontent.com/assets/13908970/9417896/6c9cfa0e-4850-11e5-9998-46f9a484e663.jpg)
![example2](https://cloud.githubusercontent.com/assets/13908970/9417895/6c9c6896-4850-11e5-83a9-2f2a8da58969.jpg)

note how some of the image is cut off, the read more-button is also not visible..
i did not change any code so i guess i'm asking if anyone else has the same issue and found a solution?
on the slippry example page the slider works fine..

**Comment by Antes** [comment]
uh images seems broken?

**Comment by shinichi11** [comment]
it's the same image so it can't be that. i also tried with other images..same problem

**Comment by sftsk** [comment]
Does the new example work right for you?
It uses `adaptiveHeight: false`, which means it only sets the height according to the first element. If your images are not the same height that can lead to unwanted behaviour.
Let me know if that helps solving your problem!
