### ISSUE TITLE
Move pager controls

### ISSUE THREAD

**Issue by snowyclo** [booncon/slippry#91]
Hi. Sorry for the novice question. I'm trying to move the pager controls so they sit under the caption and are visible over the slideshow - is this possible and please can you advise?

**Comment by sftsk** [comment]
Absolutely, you can customise everything in the css file.
Edit this file: https://github.com/booncon/slippry/blob/master/dist/slippry.css in your Slippry installation.

You are probably looking into changing `.sy-controls`.

I hope this helps,
good luck!
