### ISSUE TITLE
Do we really need all that CSS?

### ISSUE THREAD

**Issue by drewbaker** [booncon/slippry#92]
First off, slippry looks great. We have been using Cycle2, but it's getting a bit old now and breaks. What we loved about Cycle2 was how minimal it was. It allowed us to build anything, without having to do a ton of CSS overwriting, or even include a CSS file!

The Slippry CSS file is quite large comparatively, and includes a lot of default styling of things I don't want you styling (like captions, breakpoints, colors and pager buttons).

So, can you include a stylesheet with just the bare minimums?

I'd also suggest you make the transition fx's plugins or add-ons, because a lot of people won't even use KenBurns, and the stylesheet includes it always.

**Comment by sftsk** [comment]
Hello,

thank you for your thoughts. Our goal with Slippry is to ship something that works as it is for anyone who is not a CSS/ JS guru.
If you know what you are doing and don't like the styling you are welcome to use the SASS source file and style Slippry to your liking :)

The next major version will be a little more modular but in general this is our philosophy. I hope you still find our plugin useful!
