### ISSUE TITLE
Problems with fade transition and useCSS setting

### ISSUE THREAD

**Issue by lariza** [booncon/slippry#94]
Hi,
it looks like useCSS is true by default, not false (see http://slippry.com/settings/)?
Also, if I set useCSS to false, the slider won't work at all. Inspector shows some error concerning the easing effect. And if the speed is quite slow (for example 6000) and I set transition to "fade", it doesn't fade continuously in Chrome. 

I fixed this by adding the jquery ui fade effect separately to my website.

**Comment by sftsk** [comment]
Hello, thanks you for pointing this out!
The documentation is fixed now.

Regarding the js errors, I can not reproduce that. Including jQuery should be enough. At least the included demo works just fine and also quite smoothly on Chrome.

Did you perhaps add any custom markup?

**Comment by lariza** [comment]
Hi! Well, this is weird. I tested this again by removing the jquery ui (core + fade effect) and now it works fine without it! But anyway, I must set useCSS to false, because with css the slow fade transition is not smooth in Chrome. 
But yay, it works, thank you! :)

**Comment by sftsk** [comment]
Glad to hear that :)
Have a nice evening!
