### ISSUE TITLE
thumbs.getCurrentSlide(), returns object Object?

### ISSUE THREAD

**Issue by saturday1** [booncon/slippry#95]
I have tried to write out current slide number. It only returns "object Object". I do not get it how to use this object to get the actual number, "1", "2", etc. How do I get the current slide number? This is probably my lacking knowledge about javascript objects and not a script failure. Anyway, would be grateful for help.

```javascript
				jQuery('.slider-arrows').prepend('<div class="numbers"></div>');
				jQuery('.numbers').text(thumbs.getCurrentSlide() + ' / ' + thumbs.getSlideCount());
```

**Comment by sftsk** [comment]
Hello, yes, it returns the slide as an object.
You can do this to make it work:
```
jQuery('.slider-arrows').prepend('<div class="numbers"></div>');
jQuery('.numbers').text((thumbs.getCurrentSlide().index() + 1) + ' / ' + thumbs.getSlideCount());
```
All the best!
